export function translate(text) {
    let dict = {
        "home": "首頁",
        "All Products": "所有商品",
        "all": "全部",
        "Electronics": "電子產品",
        "Luggage": "行李",
        "Men's Fashion": "男性時尚",
        "Women's Fashion": "女性時尚",
        "Health and Household": "健康",
        "Home and Kitchen": "居家生活",
        "Beauty and Personal Care":"美妝護理",
        "Television & Video":"電視影音",
        "Clothing":"衣著",
        "Shoes":"鞋子",
        "Watches":"手錶",
        "Surf, Skate & Street":"休閒運動",
        "Accessories":"配件",
        "Big & Tall":"大尺碼",
        "Contemporary & Designer":"當代設計",
        "Uniforms, Work & Safety":"工作服",
        "Juniors":"年輕",
        "Petite":"小尺碼",
        "Plus-Size":"大尺碼",
        "Maternity":"孕婦裝",
        "Handbags & Wallets":"手提包",
        "Jewelry":"飾品",
        "Kids' Home Store":"孩童家具",
        "Storage & Organization":"收納整理",
        "Wall Art":"掛飾",
        "Event & Party Supplies":"派對用品",
        "Vacuums & Floor Care":"地板清潔",
        "Bedding":"寢具",
        "Bath":"浴室用品",
        "Cleaning Supplies":"清潔用品",
        "Kitchen & Dining":"廚房用品",
        "Furniture":"生活家具",
        "Home Décor": "居家裝飾",
        "Seasonal Décor":"季節性擺飾",
        "Security & Surveillance":"保全裝置",
        "Video Game Consoles & Accessories":"遊戲主機/配件",
        "Portable Audio & Video":"行動視聽裝置",
        "Office Electronics":"辦公室用品",
        "Home Audio":"家庭音響",
        "Headphones":"耳機",
        "Cell Phones & Accessories":"手機/配件",
        "GPS, Finders & Accessories":"GPS定位裝置/配件",
        "Camera & Photo":"攝影器材",
        "Car & Vehicle Electronics":"車上裝置",
        "Computers & Accessories":"電腦/配件",
        "eBook Readers & Accessories":"電子書閱讀裝置",
        "Wearable Technology":"穿戴式電子用品",
        "Hair care":"頭髮護理",
        "Skin Care":"皮膚護理",
        "Makeup":"化妝品",
        "Personal Care":"個人保養",
        "Foot, Hand & Nail Care":"指甲護理",
        "Fragrance":"香氛用品",
        "Tools & Accessories":"工具",
        "Shave & Hair Removal":"去除毛髮",
        "Travel Accessories":"旅行配件",
        "Laptop Bags":"公事包",
        "Backpacks":"後背包",
        "Umbrellas":"雨傘",
        "Medical Supplies & Equipment":"醫療用品",
        "Wellness & Relaxation":"放鬆",
        "Vision Care":"視力保養",
        "Oral Care":"口腔保養",
        "Stationery & Gift Wrapping Supplies":"禮物",
        "Health Care":"健康護理",
        "Personal Care":"個人保養",
        "Sports Nutrition":"運動補給",
        "Vitamins & Dietary Supplements":"營養補充品",
        "Household Supplies":"家庭用品",
        "Check It Out":"去看看",
        "Load More":"載入更多",
        "Product Detail":"商品頁面",
        "Add To Cart":"加入購物車",
        "Login Your Account": "登入",
        "Username": "帳號",
        "Password": "密碼",
        "Enter username...": "輸入帳號...",
        "Enter password...": "輸入密碼...",
        "Enter captcha...": "輸入驗證碼...",
        "Welcome": "歡迎",
        "Cancel": "取消",
        "Proceed": "繼續",
        "Checkout": "結帳",
        "Total": "總金額",
        "Survey": "已完成"
    }
    if(text in dict){
        return dict[text]
    }
    else{
        return text;
    }
}
  